# .pre-commit-config.yaml
#
# Universal pre-commit configuration for:
# - Python projects
# - Zig projects
# - Mixed-language projects
#
# Safe to share across repositories:
# - Hooks that find no matching files simply skip execution.
# - No failures if Zig files don’t exist in a Python repo, or vice versa.
# - Avoids committing large files accidentally.

repos:
  # -----------------------------
  # Core hygiene (all repos)
  # -----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:

      - id: check-added-large-files

      - id: check-case-conflict

      - id: check-json

      - id: check-merge-conflict

      - id: check-yaml
        # Only check YAML config in expected places
        files: ^\.github/|\.pre-commit-config\.yaml

      - id: end-of-file-fixer
        exclude: ^schemas/|^storage/

      - id: mixed-line-ending
        args: ["--fix=lf"]

      - id: trailing-whitespace
        exclude: ^schemas/|^storage/


  # -----------------------------
  # Zig formatting
  # -----------------------------
  - repo: local
    hooks:
      - id: zig-fmt
        name: zig fmt
        entry: zig fmt .
        language: system
        types: [zig]
        pass_filenames: false
        # Runs `zig fmt .` to format all files recursively

  # -----------------------------
  # Python linting/formatting
  # -----------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-check
        name: ruff check
        args: [--fix]
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        types_or: [python, pyi]
