name = "civic-dev"
version = "0.0.3"
description = "Civic Interconnect Command Line Interface."
authors = [
    { name="Civic Interconnect", email="info@civic-interconnect.org" }
]
license = { text = "MIT" }
readme = "README.md"
